name: chatkit_core
description: Dart port of ChatKit JS core client providing transport, models, and controller APIs.
version: 0.1.0
homepage: https://github.com/openai/chatkit-js
repository: https://github.com/diwakarmoturu/chatkit-dart
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  http: ^1.2.1
  meta: ^1.11.0
  collection: ^1.18.0
  json_annotation: ^4.9.0
  async: ^2.11.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  test: ^1.25.2
